name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1

    - name: Build Android library
      working-directory: android
      run: gradle clean :carlogohelper-android:assembleRelease --no-daemon --stacktrace

    - name: Run Android lint
      working-directory: android
      run: gradle :carlogohelper-android:lint --no-daemon --stacktrace

    - name: Verify AAR output
      run: |
        find android -name "*.aar" | grep -q "." && echo "AAR build successful!" || exit 1
